// form-builder/client/src/components/FormBuilderClient.tsx
"use client";
import { DndContext, closestCenter } from '@dnd-kit/core';
import
  {
    SortableContext,
    arrayMove,
    useSortable,
    verticalListSortingStrategy,
  } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { GripVertical } from 'lucide-react';
import { useEffect, useState } from 'react';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import FormRenderer from './FormRenderer';
import { InputFieldProps } from './InputField';
import { Button } from './ui/button';
import { Input } from './ui/input';
import
  {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
  } from './ui/select';

function DraggableField({ id, children }: { id: string; children: React.ReactNode }) {
  const { attributes, listeners, setNodeRef, transform, transition, isDragging } = useSortable({ id });
  return (
    <li
      ref={setNodeRef}
      style={{
        transform: CSS.Transform.toString(transform),
        transition,
        opacity: isDragging ? 0.5 : 1,
        background: isDragging ? '#f3f4f6' : undefined,
      }}
      className="flex items-center gap-2 mb-2 rounded"
      {...attributes}
    >
      <span {...listeners} className="cursor-grab p-1 text-muted-foreground">
        <GripVertical size={18} />
      </span>
      {children}
    </li>
  );
}

export default function FormBuilderClient() {
  const [fields, setFields] = useState<InputFieldProps[]>([]);
  const [newType, setNewType] = useState<'text' | 'checkbox' | 'radio'>('text');
  const [newLabel, setNewLabel] = useState('');
  const [preview, setPreview] = useState(false);
  const [loading, setLoading] = useState(false);

  async function handleSave() {
    setLoading(true);
    try {
      const res = await fetch('http://localhost:3001/forms', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(fields),
      });
      if (!res.ok) throw new Error('Failed to save');
      toast.success('Saved!');
    } catch (err: any) {
      toast.error(err.message || 'Error saving');
    } finally {
      setLoading(false);
    }
  }

  async function handleLoad() {
    setLoading(true);
    try {
      const res = await fetch('http://localhost:3001/forms');
      if (!res.ok) throw new Error('Failed to load');
      const data = await res.json();
      if (Array.isArray(data)) {
        setFields(data);
        toast.success('Loaded!');
      } else if (data && typeof data === 'object' && Object.keys(data).length === 0) {
        // If backend returns empty object, treat as empty array
        setFields([]);
        toast.success('Loaded!');
      } else if (!data) {
        setFields([]);
        toast.success('Loaded!');
      } else {
        toast.error('Invalid schema loaded');
      }
    } catch (err: any) {
      toast.error(err.message || 'Error loading');
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    handleLoad();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  function handleAddField() {
    if (!newLabel.trim()) return;
    setFields([...fields, { type: newType, label: newLabel }]);
    setNewLabel('');
  }

  function handleRemoveField(idx: number) {
    setFields(fields.filter((_, i) => i !== idx));
  }

  return (
    <>
      <ToastContainer position="top-right" autoClose={2000} />
      <div className="flex gap-2 items-center mb-4">
        <Button type="button" variant="secondary" onClick={() => setPreview(p => !p)}>
          {preview ? 'Switch to Builder Mode' : 'Switch to Preview Mode'}
        </Button>
        <Button type="button" onClick={handleSave} disabled={preview || loading}>
          {loading ? 'Saving...' : 'Save'}
        </Button>
        {/* <Button type="button" onClick={handleLoad} disabled={preview || loading}>
          {loading ? 'Loading...' : 'Load'}
        </Button> */}
      </div>

      {!preview && (
        <div className="mb-6 border rounded-md p-4">
          <h2 className="text-lg font-semibold mb-2">Add Field</h2>
          <div className="flex gap-2 items-center">
            <Select value={newType} onValueChange={v => setNewType(v as any)}>
              <SelectTrigger className="w-32">
                <SelectValue placeholder="Type" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="text">Text</SelectItem>
                <SelectItem value="checkbox">Checkbox</SelectItem>
                <SelectItem value="radio">Radio</SelectItem>
              </SelectContent>
            </Select>
            <Input
              type="text"
              placeholder="Field label"
              value={newLabel}
              onChange={e => setNewLabel(e.target.value)}
              className="flex-1"
            />
            <Button type="button" onClick={handleAddField} disabled={!newLabel.trim()}>
              Add
            </Button>
          </div>
        </div>
      )}

      {!preview && (
        <div className="mb-6">
          <h2 className="text-lg font-semibold mb-2">Fields</h2>
          {fields.length === 0 && <div className="text-muted-foreground">No fields added yet.</div>}
          <DndContext
            collisionDetection={closestCenter}
            onDragEnd={event => {
              const { active, over } = event;
              if (active.id !== over?.id) {
                const oldIndex = fields.findIndex((f, i) => f.label + f.type + i === active.id);
                const newIndex = fields.findIndex((f, i) => f.label + f.type + i === over?.id);
                if (oldIndex !== -1 && newIndex !== -1) {
                  setFields(arrayMove(fields, oldIndex, newIndex));
                }
              }
            }}
          >
            <SortableContext
              items={fields.map((f, i) => f.label + f.type + i)}
              strategy={verticalListSortingStrategy}
            >
              <ul className="list-none p-0">
                {fields.map((field, idx) => (
                  <DraggableField key={field.label + field.type + idx} id={field.label + field.type + idx}>
                    <span className="min-w-[80px] font-medium">{field.label}</span>
                    <span className="text-muted-foreground text-sm">{field.type}</span>
                    <Button type="button" variant="destructive" size="sm" onClick={() => handleRemoveField(idx)}>
                      X
                    </Button>
                  </DraggableField>
                ))}
              </ul>
            </SortableContext>
          </DndContext>
        </div>
      )}

      {preview && (
        <FormRenderer fields={fields} disabled={false} />
      )}
    </>
  );
}

// form-builder/client-vue/src/components/FormBuilderClient.vue
<template>
  <div>
    <div class="flex flex-row items-center mb-4">
      <v-btn class="mr-6" color="secondary" @click="preview = !preview" variant="flat">
        {{ preview ? 'Switch to Builder Mode' : 'Switch to Preview Mode' }}
      </v-btn>
      <v-btn color="primary" @click="handleSave" :disabled="preview || loading" variant="flat">
        {{ loading ? 'Saving...' : 'Save' }}
      </v-btn>
    </div>

    <div v-if="!preview" class="mb-6 rounded-md p-4">
      <h2 class="text-lg font-semibold mb-2">Add Field</h2>
      <div class="flex gap-2 items-center">
        <v-select
          v-model="newType"
          :items="fieldTypes"
          label="Type"
          class="w-32"
          variant="outlined"
          density="comfortable"
        />
        <v-text-field
          v-model="newLabel"
          placeholder="Field label"
          class="flex-1"
          variant="outlined"
          density="comfortable"
        />
        <v-btn color="primary" @click="handleAddField" :disabled="!newLabel.trim()" variant="flat">Add</v-btn>
      </div>
    </div>

    <div v-if="!preview" class="mb-6">
      <h2 class="text-lg font-semibold mb-2">Fields</h2>
      <div v-if="fields.length === 0" class="text-gray-400">No fields added yet.</div>
      <draggable v-model="fields" item-key="id" handle=".drag-handle" class="p-0" :animation="200">
        <template #item="{ element, index }">
          <v-sheet
            class="flex items-center gap-3 mb-3 rounded-lg shadow-sm px-4 py-2 bg-white border border-gray-200"
            elevation="1"
          >
            <v-icon class="drag-handle cursor-grab text-gray-400 mr-2" size="22">mdi-drag</v-icon>
            <span class="font-medium text-base">{{ element.label }}</span>
            <span class="text-caption text-grey-lighten-1 capitalize ml-4">{{ element.type }}</span>
            <v-btn
              color="red"
              variant="flat"
              size="small"
              class="ml-2"
              style="min-width: 32px; width: 32px; height: 32px; line-height: 1;"
              @click="handleRemoveField(index)"
            >X</v-btn>
          </v-sheet>
        </template>
      </draggable>
    </div>

    <FormRenderer v-if="preview" :fields="fields" :disabled="false" />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import FormRenderer from './FormRenderer.vue';
import { useToast } from 'vue-toastification';
import draggable from 'vuedraggable';

interface Field {
  type: 'text' | 'checkbox' | 'radio';
  label: string;
  id: string;
}

const fields = ref<Field[]>([]);
const newType = ref<'text' | 'checkbox' | 'radio'>('text');
const newLabel = ref('');
const preview = ref(false);
const loading = ref(false);
const toast = useToast();
const fieldTypes = [
  { title: 'Text', value: 'text' },
  { title: 'Checkbox', value: 'checkbox' },
  { title: 'Radio', value: 'radio' },
];

function handleAddField() {
  if (!newLabel.value.trim()) return;
  fields.value.push({ type: newType.value, label: newLabel.value, id: `${newLabel.value}-${Date.now()}` });
  newLabel.value = '';
}

function handleRemoveField(idx: number) {
  fields.value.splice(idx, 1);
}

async function handleSave() {
  loading.value = true;
  try {
    const res = await fetch('http://localhost:3001/forms', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(fields.value),
    });
    if (!res.ok) throw new Error('Failed to save');
    toast.success('Saved!');
  } catch (err: any) {
    toast.error(err.message || 'Error saving');
  } finally {
    loading.value = false;
  }
}

async function handleLoad() {
  loading.value = true;
  try {
    const res = await fetch('http://localhost:3001/forms');
    if (!res.ok) throw new Error('Failed to load');
    const data = await res.json();
    if (Array.isArray(data)) {
      fields.value = data.map((f: any, i: number) => ({ ...f, id: f.id || `${f.label}-${i}` }));
      toast.success('Loaded!');
    } else if (data && typeof data === 'object' && Object.keys(data).length === 0) {
      fields.value = [];
      toast.success('Loaded!');
    } else if (!data) {
      fields.value = [];
      toast.success('Loaded!');
    } else {
      toast.error('Invalid schema loaded');
    }
  } catch (err: any) {
    toast.error(err.message || 'Error loading');
  } finally {
    loading.value = false;
  }
}

onMounted(() => {
  handleLoad();
});
</script>

<style scoped>
.btn {
  @apply px-3 py-1 rounded bg-blue-600 text-white hover:bg-blue-700 transition disabled:opacity-50;
}
.btn-secondary {
  @apply bg-gray-200 text-gray-800 hover:bg-gray-300;
}
.btn-danger {
  @apply bg-red-600 text-white hover:bg-red-700;
}
.btn-sm {
  @apply px-2 py-0.5 text-xs;
}
</style>
