// form-builder/client/src/components/InputField.tsx
import { Checkbox } from './ui/checkbox';
import { Input } from './ui/input';
import { RadioGroup, RadioGroupItem } from './ui/radio-group';

export type InputFieldProps = {
  type: 'text' | 'checkbox' | 'radio';
  label: string;
  disabled?: boolean;
};

export default function InputField({ type, label, disabled = false }: InputFieldProps) {
  if (type === 'radio') {
    // Render a group of two radio buttons for visual clarity
    return (
      <div className="mb-4">
        <label className="block mb-1 font-medium">{label}</label>
        <RadioGroup defaultValue="option1" disabled={disabled} className="flex gap-6 ml-2">
          <div className="flex items-center gap-2">
            <RadioGroupItem value="option1" id={`${label}-option1`} disabled={disabled} />
            <label htmlFor={`${label}-option1`} className="text-sm">Option 1</label>
          </div>
          <div className="flex items-center gap-2">
            <RadioGroupItem value="option2" id={`${label}-option2`} disabled={disabled} />
            <label htmlFor={`${label}-option2`} className="text-sm">Option 2</label>
          </div>
        </RadioGroup>
      </div>
    );
  }
  if (type === 'checkbox') {
    return (
      <div className="mb-4 flex items-center gap-2">
        <Checkbox id={label} disabled={disabled} />
        <label htmlFor={label} className="text-sm font-medium">{label}</label>
      </div>
    );
  }
  // Default: text
  return (
    <div className="mb-4">
      <label className="block mb-1 font-medium" htmlFor={label}>{label}</label>
      <Input id={label} type="text" placeholder="Enter text..." disabled={disabled} />
    </div>
  );
}

// form-builder/client-vue/src/components/InputField.vue
<template>
  <div class="mb-4">
    <label class="mb-1 font-medium text-left w-full block">{{ label }}</label>
    <template v-if="type === 'radio'">
      <v-radio-group :disabled="disabled" v-model="radioValue">
        <v-radio label="Option 1" value="option1" :disabled="disabled" />
        <v-radio label="Option 2" value="option2" :disabled="disabled" />
      </v-radio-group>
    </template>
    <template v-else-if="type === 'checkbox'">
      <v-checkbox :disabled="disabled" v-model="checkboxValue" />
    </template>
    <template v-else>
      <v-text-field
        placeholder="Enter text..."
        :disabled="disabled"
        variant="outlined"
        density="comfortable"
        v-model="textValue"
        hide-details
      />
    </template>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

defineProps<{
  type: 'text' | 'checkbox' | 'radio',
  label: string,
  disabled?: boolean
}>()

const textValue = ref('');
const checkboxValue = ref(false);
const radioValue = ref('option1');
</script>
