// form-builder/client-vue/src/components/FormRenderer.vue
<template>
  <form>
    <InputField
      v-for="(field, idx) in fields"
      :key="idx"
      v-bind="field"
      :disabled="disabled"
    />
  </form>
</template>

<script setup lang="ts">
import InputField from './InputField.vue';

defineProps<{
  fields: Array<{ type: 'text' | 'checkbox' | 'radio'; label: string }>,
  disabled?: boolean
}>()
</script>

// form-builder/client/src/components/FormRenderer.tsx
import InputField, { InputFieldProps } from './InputField';

export type FormRendererProps = {
  fields: InputFieldProps[];
  disabled?: boolean;
};

export default function FormRenderer({ fields, disabled }: FormRendererProps) {
  return (
    <form>
      {fields.map((field, idx) => (
        <InputField key={idx} {...field} disabled={disabled} />
      ))}
    </form>
  );
}
